---

- name: 'update configuration'
  template:
    src: 'etc/knot/knot.conf.j2'
    dest: "{{ knot_config_file }}"
    owner: 'root'
    group: "{{ knot_group }}"
    mode: "0o640"
    validate: "{{ knot_knotc }} -c %s conf-check"
    backup: true
  notify:
    - 'knot restart'

- name: "handle zone configs"
  knot_zone:
    state: "{{ item.value.state | default('present') }}"
    database_path: "{{ knot_database }}"
    zone: "{{ item.key }}"
    zone_ttl: "{{ item.value.ttl | default('3600') }}"
    zone_soa: "{{ item.value.soa | default({}) }}"
    name_servers: "{{ item.value.name_servers | default({}) }}"
    records: "{{ item.value.records | default({}) }}"
  loop:
    "{{ knot_zones | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify:
    - 'knot reload'

...
