---

- name: installing dependencies
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ knot_dependencies }}"
  when: knot_dependencies

- name: installing knot package(s)
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ knot_packages }}"

...
