---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: repositories
  ansible.builtin.include_tasks: repositories.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: service
  ansible.builtin.include_tasks: service.yml

...
