---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux / freebsd
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: install dedendency
  package:
    name: "{{ knot_dependencies }}"
    state: present

- name: get latest system information
  setup:

# - block:
#     - name: make sure dnf is installed (only redhat based <8)
#       package:
#         name:
#           - dnf
#         state: present
#
#     - name: get latest system information
#       setup:
#   when:
#     - ansible_os_family | lower == 'redhat'
#     - ansible_distribution | lower == 'centos'
#     - ansible_distribution_version | int < 8

- name: merge knot configuration between defaults and custom
  set_fact:
    knot_config: "{{ knot_defaults_config |
      combine( knot_config, recursive=True ) }}"

...
