---

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: install dedendency
  package:
    name: "{{ knot_dependencies }}"
    state: present
  when:
    - knot_dependencies is defined
    - knot_dependencies | count > 0

- name: python support
  block:
    - name: create requirements.txt
      template:
        src: requirements.txt.j2
        dest: /tmp/knot-requirements.txt
        mode: 0660

    - name: ensure python dependecies are installed
      pip:
        requirements: /tmp/knot-requirements.txt
        state: present
        executable: pip{{ '3' if ansible_python.version.major | int == 3 else '' }}
      register: pip_install
  when:
    - knot_python_packages is defined
    - knot_python_packages | count > 0

- name: get latest system information
  setup:

- name: merge knot configuration between defaults and custom
  set_fact:
    knot_config: "{{ knot_defaults_config |
      combine( knot_config, recursive=True ) }}"

...
