---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      block:
        - name: update pacman system
          command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: create depends service
          copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_os_family | lower == 'artix linux'

      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'

    - name: ubuntu
      block:
        - name: create generic link for python
          file:
            state: link
            src: /usr/bin/python3
            dest: /usr/bin/python

    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }} / {{ ansible_distribution_release }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
